# fly.toml app configuration file generated for story-front on 2023-07-02T16:43:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "story-front"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
